apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slack-mcp-client.fullname" . }}
  labels:
    {{- include "slack-mcp-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slack-mcp-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slack-mcp-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "slack-mcp-client.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.configMap.create .Values.configMap.name }}
          args:
            - --config
            - /app/config/mcp-servers.json
          {{- end }}
          env:
            {{- if .Values.secret.create }}
            {{- if .Values.secret.name }}
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: slack-bot-token
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: slack-app-token
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: openai-api-key
            {{- else }}
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "slack-mcp-client.fullname" . }}
                  key: slack-bot-token
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "slack-mcp-client.fullname" . }}
                  key: slack-app-token
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "slack-mcp-client.fullname" . }}
                  key: openai-api-key
            {{- end }}
            {{- else }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.configMap.create .Values.configMap.name }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          {{- end }}
      {{- if or .Values.configMap.create .Values.configMap.name }}
      volumes:
        - name: config-volume
          configMap:
            {{- if .Values.configMap.create }}
            name: {{ include "slack-mcp-client.fullname" . }}-config
            {{- else }}
            name: {{ .Values.configMap.name }}
            {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
