apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slack-mcp-client.fullname" . }}
  labels:
    {{- include "slack-mcp-client.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- $key | nindent 2 }}: {{ $value | b64enc | quote }}
  {{- end }}
