{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slack-mcp-client.fullname" . }}
  labels:
    {{- include "slack-mcp-client.labels" . | nindent 4 }}
type: Opaque
data:
  slack-bot-token: {{ required "A valid .Values.env.SLACK_BOT_TOKEN is required" .Values.env.SLACK_BOT_TOKEN | b64enc | quote }}
  slack-app-token: {{ required "A valid .Values.env.SLACK_APP_TOKEN is required" .Values.env.SLACK_APP_TOKEN | b64enc | quote }}
  openai-api-key: {{ required "A valid .Values.env.OPENAI_API_KEY is required" .Values.env.OPENAI_API_KEY | b64enc | quote }}
{{- end }}
