{{- if and .Values.networkPolicy.enabled (.Values.networkPolicy.type | eq "cilium") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-mcp-client.fullname" . }}
  labels:
    {{- include "slack-mcp-client.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "slack-mcp-client.selectorLabels" . | nindent 4 }}
  ports:
    - port: 1111 # Dummy port required to create the service
  sessionAffinity: None
  type: ClusterIP
{{- end }}
