{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slack-mcp-client.fullname" . }}
  labels:
    {{- include "slack-mcp-client.labels" . | nindent 4 }}
{{- end }}
